name: daily_report
on: [push]
jobs:
  notify_line:
    runs-on: ubuntu-latest
    steps:
    - uses: snow-actions/line-notify@v1.0.0
      with:
        token: ${{ secrets.LINE_TOKEN }}
        message: "test"
