name: daily_report
on: [push]
jobs:
  notify_line:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test"
      with:
        secrets: 
          access-token: ${{ secrets.LINE_TOKEN }}
        message: "test"
