name: daily_report
on: [push]
jobs:
  notify_line:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test"
      env: 
        TITLE: "test"
      secrets: 
        access-token: ${{ secrets.LINE_TOKEN }}
