name: daily_report
on: 
  push:
    branches:
      -main
jobs:
  notify_line:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/chechout@v2

    - name: input_file
      uses: juliangruber/read-file-action@v1
      with:
        path: ./README.md

    - name: send LINE Notify
      env: 
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        URL: https://notify-api.line.me/api/notify
      run: |
        curl -X POST -H 'Authorization: Bearer {$LINE_TOKEN}' -F 'message=${{ steps.package.outputs.content }}' \
        ${URL}
      
