name: daily_report
on: [push]
jobs:
  notify_line:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v36

    - name: echo change file
      run: echo "${{ steps.changed-files.outputs.modified_files }}"

    - name: input file
      id: file
      uses: juliangruber/read-file-action@v1
      with:
        path: ./"${{ steps.changed-files.outputs.modified_files }}"

    - name: echo
      run: echo "${{ steps.file.outputs.content }}"

    - name: send LINE Notify
      env: 
        URL: https://notify-api.line.me/api/notify
      run: |
        curl -X POST -H 'Authorization: Bearer ${{secrets.LINE_TOKEN }}' -F 'message=${{ steps.file.outputs.content }}' \
        ${URL}
      
