name: daily_report
on: [push]
jobs:
  notify_line:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v36
      
    - name: List all added files
      run: |
        for file in ${{ steps.changed-files.outputs.added_files }}; do
        if [ $file = *.md ]; then
          echo $file
        else
          echo ".mdではない"
        fi
        done
        
    - name: send LINE Notify
      if: ${{ !startsWith(steps.changed-files.outputs.add_files, 'README') }}
      run: |
        sed -i 's/[\#\>]//g' ./${{ steps.changed-files.outputs.added_files }}
        val=$(cat ./${{ steps.changed-files.outputs.added_files }})
        curl -X POST -H 'Authorization: Bearer ${{ secrets.LINE_TOKEN }}' -F "message=$val"\
        ${{ secrets.LINE_URL }}
      
